<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hwpx .hwpx -  ( )</name>
   <tag></tag>
   <elementGuidId>fce484af-06d4-4961-91ef-02d4ae564cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.file_name.text_align_center.inline_panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title_bar']/div[2]/div[2]/div/div
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef23ada0-4d2c-483c-8273-2b3c7ac44fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_name text_align_center inline_panel</value>
      <webElementGuid>0815a534-674e-49ec-adf7-11c4f779f4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>file_name</value>
      <webElementGuid>f562119d-f001-459e-871a-c6fa39b74b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hwpx 보기권한.hwpx - 한글 (읽기 전용)</value>
      <webElementGuid>94bdbf9f-daa6-4e95-b066-8f604beef3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_bar&quot;)/div[@class=&quot;top_title normal_panel&quot;]/div[@class=&quot;guide inline_panel&quot;]/div[@class=&quot;normal_panel align_item_center&quot;]/div[@class=&quot;file_name text_align_center inline_panel&quot;]</value>
      <webElementGuid>39f22b56-3c3d-4a77-b294-2afbcc93a71a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title_bar']/div[2]/div[2]/div/div</value>
      <webElementGuid>9a3e1285-29e0-451a-aeb5-c7a2e18a07ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='파일'])[1]/preceding::div[1]</value>
      <webElementGuid>ecf775ee-c96b-4f10-9e86-ddde99c145e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='다운로드'])[1]/preceding::div[3]</value>
      <webElementGuid>69f80f49-60a0-4da9-b842-6636cfa518f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hwpx 보기권한.hwpx - 한글 (읽기 전용)']/parent::*</value>
      <webElementGuid>f9088103-8afd-4db5-ae8f-98f81aa810cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>c600396b-4079-432d-806b-d01b5a6f7e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'hwpx 보기권한.hwpx - 한글 (읽기 전용)' or . = 'hwpx 보기권한.hwpx - 한글 (읽기 전용)')]</value>
      <webElementGuid>881e6b71-2698-4b8a-b711-eb1660d32fab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
