<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test_입력</name>
   <tag></tag>
   <elementGuidId>ae27c99c-03b0-4a9c-87bf-102a3c6fe1c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;insert&quot;] > div.property_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title_bar']/div[3]/div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34352eeb-edb1-4421-9aac-e88ca378ebf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>property_title</value>
      <webElementGuid>2f34fbe2-bc29-401d-9a5b-f66c9173e616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-command</name>
      <type>Main</type>
      <value>title_bar</value>
      <webElementGuid>9737cbf7-4791-4d35-a165-a4cf69ab479a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-value</name>
      <type>Main</type>
      <value>insert</value>
      <webElementGuid>6254d115-ca64-4398-8983-a5ac0173c72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>입력</value>
      <webElementGuid>41b62f60-faf3-4967-8ad3-ea776b14adb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_bar&quot;)/div[@class=&quot;bottom_title normal_panel&quot;]/div[@class=&quot;insert_view title_panel on&quot;]/div[@class=&quot;property_title&quot;]</value>
      <webElementGuid>d44ce929-f164-42d0-8291-8a2b1dcca94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title_bar']/div[3]/div[5]/div</value>
      <webElementGuid>89e89167-34b5-494d-95fe-a0fdd2a08de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='메모 안내선 표시'])[1]/following::div[2]</value>
      <webElementGuid>421f31f3-85ce-48a5-83a7-597138b513cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='모든 메모 표시'])[1]/following::div[4]</value>
      <webElementGuid>edc9c07d-9df9-4340-8137-cd24430cd1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도형'])[1]/preceding::div[2]</value>
      <webElementGuid>c1c7d70d-4230-4e47-9a4c-e5101c3417a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div[5]/div</value>
      <webElementGuid>21d4c168-34fe-4fa2-8aa2-ed7c9b21e8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '입력' or . = '입력')]</value>
      <webElementGuid>1ef84d5f-e97e-4a2b-9d9e-db4ae71b36c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
