<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppStore_apple_txt</name>
   <tag></tag>
   <elementGuidId>57b751ab-ca3b-41d4-8128-5b596e261696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.we-localnav__title__product</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='localnav']/div/div[2]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3ac0b044-2579-4f5a-a5f5-453d4dc1b197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>we-localnav__title__product</value>
      <webElementGuid>209dbbf5-069e-44d4-9b1d-2600d6736245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>App Store</value>
      <webElementGuid>b33043bb-fa10-4179-98ba-3e29b4619eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;localnav&quot;)/div[@class=&quot;localnav-wrapper&quot;]/div[@class=&quot;localnav-content we-localnav__content&quot;]/div[@class=&quot;localnav-title we-localnav__title&quot;]/a[1]/span[@class=&quot;we-localnav__title__product&quot;]</value>
      <webElementGuid>61ba9926-239d-427a-b98a-27cd0034148c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='localnav']/div/div[2]/div/a/span</value>
      <webElementGuid>58854c24-b185-4c2a-98c1-d21b064481f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::span[2]</value>
      <webElementGuid>dc1f468b-0960-4d2c-bb79-a57b05baac2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/following::span[14]</value>
      <webElementGuid>6c326373-b2e1-433d-ab6d-fcfac5980ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::span[1]</value>
      <webElementGuid>43a28f87-7937-499d-95b3-91e1ae94e3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>ce74a026-b5b7-467d-a612-04ebc30030a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'App Store' or . = 'App Store')]</value>
      <webElementGuid>fb082c5c-3da6-4537-82f2-22083bf3e9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
