<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppStore_apple_txt</name>
   <tag></tag>
   <elementGuidId>57b751ab-ca3b-41d4-8128-5b596e261696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='localnav']/div/div[2]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.we-localnav__title__product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e216167-a1d0-4584-a803-04a7afa40dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>we-localnav__title__product</value>
      <webElementGuid>72b2be10-16ad-46f0-a744-f9b194ac87fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>App Store</value>
      <webElementGuid>04f2b193-42a9-4b24-9ea0-172393922e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;localnav&quot;)/div[@class=&quot;localnav-wrapper&quot;]/div[@class=&quot;localnav-content we-localnav__content&quot;]/div[@class=&quot;localnav-title we-localnav__title&quot;]/a[1]/span[@class=&quot;we-localnav__title__product&quot;]</value>
      <webElementGuid>270345d0-2db6-4c44-aa22-33792eb40adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='localnav']/div/div[2]/div/a/span</value>
      <webElementGuid>88254488-ff09-4aff-9369-bd281f9db9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::span[2]</value>
      <webElementGuid>d5854589-0b97-4b62-b99b-23cc937edb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/following::span[14]</value>
      <webElementGuid>325e8743-e37a-42f0-b8d4-1c2e12969d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::span[1]</value>
      <webElementGuid>56e1e8ca-bfd1-4687-ba06-55059ddc7bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>75b1b626-89f0-45c6-8049-38d6d27dd1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'App Store' or . = 'App Store')]</value>
      <webElementGuid>ef62638a-7bb1-4006-8e67-12018242e187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
