<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MainCopy</name>
   <tag></tag>
   <elementGuidId>62ab66e7-190f-4066-9e81-00bfb53a28d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.MuiTypography-root.MuiTypography-h2.css-6w5kag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/section/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b16675c0-415b-4a74-ba3d-b1b334f66931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h2 css-6w5kag</value>
      <webElementGuid>58d489bc-02bd-4680-9566-6e413f63680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>이제 한컴오피스 구독으로</value>
      <webElementGuid>8534ba50-80e7-4cd6-acda-598f6c400e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-1j23mgk&quot;]/main[@class=&quot;MuiBox-root css-hngt96&quot;]/div[@class=&quot;MuiBox-root css-1t9hyv3&quot;]/section[@class=&quot;css-160flv4&quot;]/div[@class=&quot;MuiBox-root css-1pc1w1t&quot;]/h2[@class=&quot;MuiTypography-root MuiTypography-h2 css-6w5kag&quot;]</value>
      <webElementGuid>4ec45668-3607-4d3a-a497-f6c4001ee1e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/section/div/h2</value>
      <webElementGuid>70fcf142-81e5-432c-ab45-93994278766d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이용권 등록하기'])[1]/following::h2[1]</value>
      <webElementGuid>f7b8e85b-80ef-438c-9fb1-cfbf3c1e64e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구독하기'])[1]/following::h2[1]</value>
      <webElementGuid>93f74b85-45d8-4a5e-9ca4-f72b46f54166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구독하기'])[2]/preceding::h2[1]</value>
      <webElementGuid>17f4b749-ecdd-44a1-89d2-71c8db7f238f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='한컴오피스가 구독형 서비스인 한컴독스로 새롭게 바뀌었어요.'])[1]/preceding::h2[1]</value>
      <webElementGuid>26b5ea3b-d40d-4bd2-91ac-84b1868b4ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='이제 한컴오피스 구독으로']/parent::*</value>
      <webElementGuid>fc1f2d6b-ec66-4578-9e81-6bda20320a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>6458ca33-3ab1-4c53-b98d-55a2376b38f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '이제 한컴오피스 구독으로' or . = '이제 한컴오피스 구독으로')]</value>
      <webElementGuid>0cee087b-4512-4c58-ae90-73325d845f5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
