<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plancompare_title</name>
   <tag></tag>
   <elementGuidId>befe89fd-a75f-4409-a96c-9a31c09a0c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.MuiTypography-root.MuiTypography-h5.css-nw8w3k</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/section[3]/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>bee50b26-7737-4337-a36a-003f593964a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5 css-nw8w3k</value>
      <webElementGuid>ab7cd4e0-bafb-49f3-82ed-2e8032ca634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>요금제 비교</value>
      <webElementGuid>b2ee3082-b709-4170-b2d3-ce21d7ae6b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-1j23mgk&quot;]/main[@class=&quot;MuiBox-root css-hngt96&quot;]/div[@class=&quot;MuiBox-root css-1t9hyv3&quot;]/section[@class=&quot;css-5cbihu&quot;]/div[@class=&quot;MuiBox-root css-1pc1w1t&quot;]/h5[@class=&quot;MuiTypography-root MuiTypography-h5 css-nw8w3k&quot;]</value>
      <webElementGuid>013796bf-4739-4d43-9ea8-1021377f382f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/section[3]/div/h5</value>
      <webElementGuid>1a200149-2eaa-4cb8-822d-eb451acd34e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₩99,000원/년으로 구독'])[1]/following::h5[1]</value>
      <webElementGuid>027cfb44-4d75-47c0-9827-eeae15477b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='또는'])[2]/following::h5[1]</value>
      <webElementGuid>6418295e-8dc5-40ae-8226-9561d5336270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기본 항목'])[1]/preceding::h5[1]</value>
      <webElementGuid>38eab5a6-a8f5-4648-a350-be781af047e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='무료'])[2]/preceding::h5[1]</value>
      <webElementGuid>c31848dc-684d-48e9-bff8-04d23826ca78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='요금제 비교']/parent::*</value>
      <webElementGuid>128f92fe-a6ed-4ca1-865f-c869ec18e8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>6496cb3a-6b8b-4f4e-af59-030d5b9df8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = '요금제 비교' or . = '요금제 비교')]</value>
      <webElementGuid>6c87a34b-f78c-485c-a303-9ca52598425a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
