<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlayStore_google_txt</name>
   <tag></tag>
   <elementGuidId>bd7e4a9b-c575-4fac-8e26-cb0d3ef4ef85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//c-wiz[@id='kO001e']/header/nav/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f70e1e44-9799-48e3-9593-2c31fb2d8127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6cc1522-465a-4355-9878-45087a0ff482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>google_logo Play</value>
      <webElementGuid>2359e63c-f24e-4ccc-9b5b-fbd5201516d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kO001e&quot;)/header[@class=&quot;S3WLMd&quot;]/nav[@class=&quot;oPjgQb&quot;]/a[@class=&quot;f0UV3d&quot;]/span[1]</value>
      <webElementGuid>cae74595-e126-4718-8322-6b1dfa82ca1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//c-wiz[@id='kO001e']/header/nav/a/span</value>
      <webElementGuid>876c7d43-019a-43eb-acb8-978397984dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='게임'])[1]/preceding::span[1]</value>
      <webElementGuid>76f440ef-e7ae-4354-91df-2b929d99437e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='앱'])[1]/preceding::span[6]</value>
      <webElementGuid>01659b53-d7e8-4ba1-a852-009aba2d28d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='google_logo Play']/parent::*</value>
      <webElementGuid>99e3ec8e-6897-4dcd-b01d-07f68981a2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>522b6d6b-025b-4e81-b1b7-0d37da34db77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'google_logo Play' or . = 'google_logo Play')]</value>
      <webElementGuid>6e2a2099-1791-479b-8c88-f794061b0715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
