<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlayStore_google_txt</name>
   <tag></tag>
   <elementGuidId>bd7e4a9b-c575-4fac-8e26-cb0d3ef4ef85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//c-wiz[@id='kO001e']/header/nav/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43495feb-5c2e-4bc8-8f80-d266882b98f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b38b4627-6f0b-4a68-80e4-0d2bb8e249c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>google_logo Play</value>
      <webElementGuid>862c7703-9f5f-4797-b7b9-42753c9add01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kO001e&quot;)/header[@class=&quot;S3WLMd&quot;]/nav[@class=&quot;oPjgQb&quot;]/a[@class=&quot;f0UV3d&quot;]/span[1]</value>
      <webElementGuid>52a8d9be-2965-4ba0-9419-a8a8a33741b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//c-wiz[@id='kO001e']/header/nav/a/span</value>
      <webElementGuid>7578b533-02c0-49fe-908a-7150e497a787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='게임'])[1]/preceding::span[1]</value>
      <webElementGuid>75fe53f3-e085-4d8b-89b6-b0a4880d8f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='앱'])[1]/preceding::span[6]</value>
      <webElementGuid>d9d96b09-6a4f-4549-9884-7f2ec0a1eb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='google_logo Play']/parent::*</value>
      <webElementGuid>c483ee06-1aba-45ae-b504-3db375d999ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>5268f588-be8d-48f4-981f-71c506685127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'google_logo Play' or . = 'google_logo Play')]</value>
      <webElementGuid>c9acc593-1ca7-4533-b7f1-23aa48d32f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
