<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>f54f2b0b-a8d7-446b-8198-6bd49531438b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.property_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title_bar']/div[3]/div/div
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>05ee3a9d-7ccf-4547-a2f4-bb2038876378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>property_title</value>
      <webElementGuid>c814ef2a-1411-4aeb-9ae7-1386f167c51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-command</name>
      <type>Main</type>
      <value>title_bar</value>
      <webElementGuid>7292fa24-bd56-4ced-87a9-ddf24442064d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-value</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>db3c4de3-bb05-4c99-b882-9003ad55bc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>파일</value>
      <webElementGuid>821ca6ce-67e7-47e6-a79d-7c36e81ae3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_bar&quot;)/div[@class=&quot;bottom_title normal_panel&quot;]/div[@class=&quot;file_view title_panel on&quot;]/div[@class=&quot;property_title&quot;]</value>
      <webElementGuid>e205e18c-9f00-47ee-96dd-0748f095e3f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title_bar']/div[3]/div/div</value>
      <webElementGuid>2076e218-21da-416a-bd64-7f301289efc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='한쇼 정보...'])[1]/following::div[3]</value>
      <webElementGuid>e73aa775-ac81-458d-b4d4-20681477d3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/following::div[4]</value>
      <webElementGuid>c360d059-c1f5-4a98-a862-86249d0bfe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='저장하기'])[1]/preceding::div[2]</value>
      <webElementGuid>f7acb1e9-e100-415a-83af-409b6cda37a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div</value>
      <webElementGuid>af7c260e-8ebe-4b35-8fb9-b54770ba2f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '파일' or . = '파일')]</value>
      <webElementGuid>16bea081-cf32-4a3b-8bb5-80025c3bba95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
