<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>e9d1cf20-8ade-4a1d-8ebd-6d50ece9fa0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.property_title > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title_bar']/div[3]/div/div/span
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a074c1b8-9c7a-49c6-9d9b-7908c5002ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>파일</value>
      <webElementGuid>5c4857f1-0617-4f55-b85d-faba05e6c817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_bar&quot;)/div[@class=&quot;bottom_title normal_panel&quot;]/div[@class=&quot;file_view title_panel on&quot;]/div[@class=&quot;property_title&quot;]/span[1]</value>
      <webElementGuid>9ffd78d5-33ae-4752-bd4f-fad3499f3477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title_bar']/div[3]/div/div/span</value>
      <webElementGuid>ad0022fc-d964-4e0d-b6f3-5cc96146cb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='한쇼 정보...'])[1]/following::span[1]</value>
      <webElementGuid>45651747-26fc-45c3-a713-2ec723e840cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/following::span[2]</value>
      <webElementGuid>e5bd8a0f-ab85-4f05-bba0-7b91ef00f924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='저장하기'])[1]/preceding::span[1]</value>
      <webElementGuid>4e8014f3-7792-4d9b-985b-917e0d1481e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ctrl+S'])[1]/preceding::span[2]</value>
      <webElementGuid>6efbb87f-9de3-499e-a8cd-ffaf785167b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='파일']/parent::*</value>
      <webElementGuid>cf35877b-1d93-4121-966d-cf8f2379c937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>5dd089ea-d1f7-42a3-acdf-12cb3f875894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '파일' or . = '파일')]</value>
      <webElementGuid>e52c93b1-724d-472a-9fe6-96a785050d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
