<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__hcwoViewScroll</name>
   <tag></tag>
   <elementGuidId>27454d6f-b5b0-49c5-ac9f-a1d3e11def73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hcwoViewScroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;title_bar&quot;]/div[3]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74874d0d-ab7f-4726-b5fb-f07f7a17cfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hcwoViewScroll</value>
      <webElementGuid>44e2f2b2-3616-46d8-9f6e-58f9f32c29dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hcwoViewScroll&quot;)</value>
      <webElementGuid>5fc3c656-f520-41c5-8d95-6822c7825a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='hcwoViewScroll']</value>
      <webElementGuid>f5c9caad-7893-4136-89fc-8b9ff852e9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='document']/div[2]/div[2]</value>
      <webElementGuid>c711c3b2-781b-448e-a530-b55881ee212d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::div[109]</value>
      <webElementGuid>79146f48-fcc2-4495-92d8-b14df886a203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='확인'])[2]/following::div[206]</value>
      <webElementGuid>8b34455d-f409-4a3c-867a-ee82cc660bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='다시 보지 않기'])[1]/preceding::div[15]</value>
      <webElementGuid>d6a156f4-0732-4aca-850e-3edb0a33b21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::div[20]</value>
      <webElementGuid>46a22172-0763-45fb-9498-01dd7f20111d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>ae0e36b8-705c-4347-9bcc-a8148eb68f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hcwoViewScroll']</value>
      <webElementGuid>369a7f25-24e2-4905-9519-85f11906be4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
