<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>8972e5fc-78b4-459f-b144-51f52223aa0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.property_title > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title_bar']/div[3]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d9c681d-b3e0-433a-80e5-ebb961998316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>파일</value>
      <webElementGuid>1de67656-7852-4d9e-baac-147986d6104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_bar&quot;)/div[@class=&quot;bottom_title normal_panel&quot;]/div[@class=&quot;file_view title_panel on&quot;]/div[@class=&quot;property_title&quot;]/span[1]</value>
      <webElementGuid>3e528a22-de5e-41fb-911d-6d1174f5a6d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title_bar']/div[3]/div/div/span</value>
      <webElementGuid>fea8762d-d064-4951-830b-a0e5b04b7ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='한글 정보...'])[1]/following::span[1]</value>
      <webElementGuid>b1a06b70-92eb-4470-a36b-ff90d7e6f748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/following::span[2]</value>
      <webElementGuid>1785f2ed-5dee-489f-8cc2-9158dbc0c65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='저장하기'])[1]/preceding::span[1]</value>
      <webElementGuid>fd9cdc77-f27e-4d27-b7ab-c1c2536fc27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ctrl+S'])[1]/preceding::span[2]</value>
      <webElementGuid>34c1a887-5167-421d-b7de-17870f9313ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='파일']/parent::*</value>
      <webElementGuid>d6e20d01-1b64-4fbf-9dfd-79d35bbe21da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>5a13716d-f635-4d54-afac-39e86fff2b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '파일' or . = '파일')]</value>
      <webElementGuid>2616419d-c526-4b5e-a6b1-f3bb97295280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
