<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test_파일</name>
   <tag></tag>
   <elementGuidId>792645bc-0c37-4bb2-91ba-7991665f0078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.property_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title_bar']/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50e4cef6-df26-4fd4-96a0-cbb90edd615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>property_title</value>
      <webElementGuid>20994b9f-4db9-423e-af92-f024d88be449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-command</name>
      <type>Main</type>
      <value>title_bar</value>
      <webElementGuid>ae14014b-7f80-4103-b0c0-284f814727af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-value</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>2b869218-44b9-4783-847b-11b0bf5f6661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>파일</value>
      <webElementGuid>c3c408f3-e5cb-4d5b-a440-641fc2c47390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_bar&quot;)/div[@class=&quot;bottom_title normal_panel&quot;]/div[@class=&quot;file_view title_panel on&quot;]/div[@class=&quot;property_title&quot;]</value>
      <webElementGuid>de65fee5-c094-4bc9-98cf-43dfdc312dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title_bar']/div[3]/div/div</value>
      <webElementGuid>3068d2f0-66de-446c-b440-57fb897a56a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='한글 정보...'])[1]/following::div[3]</value>
      <webElementGuid>202762d4-0dc3-4a49-b271-8a398e963488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도움말'])[1]/following::div[4]</value>
      <webElementGuid>709b42de-5c93-40c0-a315-ad871ee8eb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='저장하기'])[1]/preceding::div[2]</value>
      <webElementGuid>4a79274e-20e4-41ff-a71c-6cc6c0714bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div</value>
      <webElementGuid>a639cf1e-d3e4-4299-b8d2-b3f5effdbf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '파일' or . = '파일')]</value>
      <webElementGuid>6b976694-385d-439b-a824-f3016f7dba0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
