<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contactus_title_txt</name>
   <tag></tag>
   <elementGuidId>5781568f-6fe5-4416-81da-de0dc3f7e62c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.MuiTypography-root.MuiTypography-h1.css-tzyp5e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[(text() = '문의하기' or . = '문의하기')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>791d01e6-b732-4707-8042-5aa477beb2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h1 css-tzyp5e</value>
      <webElementGuid>dce78515-4129-47c6-8526-acda2742140a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>문의하기</value>
      <webElementGuid>991a9a75-2989-4615-85b6-0ef2b81b0a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-1j23mgk&quot;]/main[@class=&quot;MuiBox-root css-hngt96&quot;]/div[@class=&quot;MuiBox-root css-1rywp48&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-undefined css-1d3bbye&quot;]/h1[@class=&quot;MuiTypography-root MuiTypography-h1 css-tzyp5e&quot;]</value>
      <webElementGuid>d15e2105-f7e1-4b51-8fa3-ce581777c233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/h1</value>
      <webElementGuid>73a65d9d-6831-4aae-81cd-f72d609667ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::h1[1]</value>
      <webElementGuid>1f2b54e5-83d2-418e-987c-41f0b3c5ffd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='문의하기']/parent::*</value>
      <webElementGuid>3d698c98-b57d-41e3-9cac-776bdf6b81e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>159cd7b5-fa1f-4e46-8f76-4fc91983347a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '문의하기' or . = '문의하기')]</value>
      <webElementGuid>3b83b21d-0742-47e9-9133-7625eecfce38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
