<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FAQ_title_txt</name>
   <tag></tag>
   <elementGuidId>564773d1-9a23-40ec-baa1-e7236d72b4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@placeholder = 'Untitled' and (text() = '한컴독스 FAQ' or . = '한컴독스 FAQ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ec6d9335-e45d-4ff3-824d-6db31d65ede7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>b556707a-5f98-4be6-9204-452f29f6989b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f075f3a-bdd4-4a89-8548-773097b0b816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66cdb7df-e147-41d4-9d4b-538cc0dfbb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Untitled</value>
      <webElementGuid>5fce7ab5-25b1-4103-b7c1-ab7f74036828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f27e6427-1732-4a7f-bdfc-e19915561cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>한컴독스 FAQ</value>
      <webElementGuid>c5c195bd-7d1c-49e9-b1a2-c42185de5f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-0&quot;]/div[1]/div[@class=&quot;notion-app&quot;]/div[@class=&quot;notion-app-inner notion-light-theme&quot;]/div[@class=&quot;notion-frame&quot;]/div[@class=&quot;notion-scroller vertical horizontal&quot;]/div[1]/div[@class=&quot;width padding&quot;]/div[@class=&quot;notion-page-block&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>83df5a14-2c99-4a8f-a547-f47394f940c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div[2]/div/div/div[3]/h1</value>
      <webElementGuid>8b3cfb85-50ee-4903-a090-c3b4a1e4d8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='❓'])[1]/following::h1[1]</value>
      <webElementGuid>1af49cb8-c7d3-43c5-9a94-a740ac0e3a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='릴리즈 노트'])[2]/following::h1[1]</value>
      <webElementGuid>b192d9af-2cd8-4370-ae07-a105da946cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가장 많이 찾는 키워드'])[1]/preceding::h1[1]</value>
      <webElementGuid>94de122a-ba9a-458a-a8ff-568a5d7b8042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#사용환경'])[1]/preceding::h1[1]</value>
      <webElementGuid>7b953746-5614-4987-924c-037cc79611a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ccb1712c-1039-470b-bcea-037221902d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@placeholder = 'Untitled' and (text() = '한컴독스 FAQ' or . = '한컴독스 FAQ')]</value>
      <webElementGuid>2a354ec6-3339-4530-ac53-8fc63f5d24ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
