<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_ppt 1 503KBhwp 2 1.6MBhwpx 5 lBCiqL20K_2e2099</name>
   <tag></tag>
   <elementGuidId>28b9e90b-55de-4f4d-9bbe-a57d863ecbfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.MuiBox-root.css-1lscubz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>00c829b3-c207-4498-8754-97f79ee3d604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1lscubz</value>
      <webElementGuid>643fc70b-db87-4609-991e-f5e9bf8aba6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>홈앱 다운로드최근공유즐겨찾기필터문서 업로드이름열어 본 날짜소유자크기ppt파일 테스트1분 전나503KBhwp파일 테스트2분 전나1.6MBhwpx 편집권한5분 전lBCiqL20KBhwpx 보기권한5분 전lBCiqL20KBpdf파일 테스트5시간 전나413KBhwpx파일 테스트5시간 전나363KBshow파일 테스트6시간 전나215KBpptx파일 테스트6시간 전나27KBods파일 테스트6시간 전나15KBxlsx파일 테스트6시간 전나16KBxls파일 테스트6시간 전나31KBdoc파일 테스트6시간 전나49KBcell파일 테스트6시간 전나26KBdocx파일 테스트6시간 전나23KBodp파일 테스트6시간 전나28KBowpml파일 테스트6시간 전나85KBhfrm파일 테스트5일 전나20Byte0개 항목 이동</value>
      <webElementGuid>b76fca95-746b-4945-99c3-658c4c0fed12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-1ixckvq&quot;]/main[@class=&quot;MuiBox-root css-1lscubz&quot;]</value>
      <webElementGuid>c098da2d-e187-4ff0-affc-3c5ba18beea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main</value>
      <webElementGuid>6d0e043d-8659-42f7-9bcb-34ad6d8be564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='활동'])[1]/following::main[1]</value>
      <webElementGuid>5087a781-a399-48b7-9e94-8e08f98494de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='상세'])[1]/following::main[1]</value>
      <webElementGuid>57aa3f55-750c-4305-a26f-8ac3a0778955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main</value>
      <webElementGuid>03989c21-f902-4278-a117-e0ae5a5c57c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//main[(text() = '홈앱 다운로드최근공유즐겨찾기필터문서 업로드이름열어 본 날짜소유자크기ppt파일 테스트1분 전나503KBhwp파일 테스트2분 전나1.6MBhwpx 편집권한5분 전lBCiqL20KBhwpx 보기권한5분 전lBCiqL20KBpdf파일 테스트5시간 전나413KBhwpx파일 테스트5시간 전나363KBshow파일 테스트6시간 전나215KBpptx파일 테스트6시간 전나27KBods파일 테스트6시간 전나15KBxlsx파일 테스트6시간 전나16KBxls파일 테스트6시간 전나31KBdoc파일 테스트6시간 전나49KBcell파일 테스트6시간 전나26KBdocx파일 테스트6시간 전나23KBodp파일 테스트6시간 전나28KBowpml파일 테스트6시간 전나85KBhfrm파일 테스트5일 전나20Byte0개 항목 이동' or . = '홈앱 다운로드최근공유즐겨찾기필터문서 업로드이름열어 본 날짜소유자크기ppt파일 테스트1분 전나503KBhwp파일 테스트2분 전나1.6MBhwpx 편집권한5분 전lBCiqL20KBhwpx 보기권한5분 전lBCiqL20KBpdf파일 테스트5시간 전나413KBhwpx파일 테스트5시간 전나363KBshow파일 테스트6시간 전나215KBpptx파일 테스트6시간 전나27KBods파일 테스트6시간 전나15KBxlsx파일 테스트6시간 전나16KBxls파일 테스트6시간 전나31KBdoc파일 테스트6시간 전나49KBcell파일 테스트6시간 전나26KBdocx파일 테스트6시간 전나23KBodp파일 테스트6시간 전나28KBowpml파일 테스트6시간 전나85KBhfrm파일 테스트5일 전나20Byte0개 항목 이동')]</value>
      <webElementGuid>562cc44f-981d-4e9f-8e50-d6573c478a71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
