<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hfrm_question_tab</name>
   <tag></tag>
   <elementGuidId>ccc60068-3c7c-4017-b01b-ea7a2a86448d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrollable-auto-tab-question</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scrollable-auto-tab-question']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e85338aa-0453-4b44-8529-95dfeca23547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root jss15 MuiTab-textColorInherit STTab Mui-selected jss16 MuiTab-labelIcon</value>
      <webElementGuid>732e679d-e271-46a1-a330-46e2907bb6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80bac6db-8a99-44ca-accf-504c5031aca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02ebacfd-89e0-487a-a8ca-4f266c752f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ba2e9e50-92b6-444c-8226-d8779321af53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d26ce013-69a9-4655-a687-391c99871378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scrollable-auto-tab-question</value>
      <webElementGuid>e654ea27-7b83-4275-b994-ea937368923d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>scrollable-auto-tabpanel-question</value>
      <webElementGuid>e33534e4-b3c5-4798-b7ee-6be72c57a000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>질문</value>
      <webElementGuid>ef3995a5-ed8d-44c7-9ede-d5de7da41171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollable-auto-tab-question&quot;)</value>
      <webElementGuid>c4993d6b-b7f7-4052-94b6-413375df2a6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='scrollable-auto-tab-question']</value>
      <webElementGuid>4181806e-cdc5-4144-afbe-5129e552a6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/button</value>
      <webElementGuid>c6ef98b0-82e2-4d64-8783-e4a5c74b461e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='보내기'])[1]/following::button[1]</value>
      <webElementGuid>9e912cb7-44b9-4530-88e6-a2a2a6e3a6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='설정'])[1]/following::button[2]</value>
      <webElementGuid>52983dca-2538-4d30-a253-d67a693f95bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='결과'])[1]/preceding::button[1]</value>
      <webElementGuid>c1f9ba67-4bfe-494d-8553-c249ee1bc375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>1e1e1714-6293-407a-9e81-0138d73e182a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'scrollable-auto-tab-question' and (text() = '질문' or . = '질문')]</value>
      <webElementGuid>0158c833-ab0d-43bb-b817-c23d7f59c955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
