<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>viewer_audio_check</name>
   <tag></tag>
   <elementGuidId>6626f683-cfc3-4e6f-8293-538e4aacad14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div[3]/div/div[1]/div/audio</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1d45h3o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7d45876-ae2b-4ab7-a108-b291a43e025d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1d45h3o</value>
      <webElementGuid>d53c99fb-309b-41c0-a6d1-8c4866ec0e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root MuiDialog-root css-ve8d41&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm MuiDialog-paperFullScreen css-cc4x4&quot;]/div[@class=&quot;css-1d45h3o&quot;]</value>
      <webElementGuid>f27bbcd1-148b-4196-a25a-a6bff6c9a989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='다운로드'])[2]/following::div[1]</value>
      <webElementGuid>da648739-8253-48e2-87ad-82133d97e515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='필터 초기화'])[1]/following::div[10]</value>
      <webElementGuid>fd240721-7d42-49f7-9b7c-9c7ec62b9f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div</value>
      <webElementGuid>3c98564d-fa05-486f-9b18-e5b862de2719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
